/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>case limb</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.case_limb#getCase_list <em>Case list</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.case_limb#getStmt <em>Stmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getcase_limb()
 * @model
 * @generated
 */
public interface case_limb extends EObject
{
  /**
   * Returns the value of the '<em><b>Case list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case list</em>' containment reference.
   * @see #setCase_list(case_label_list)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getcase_limb_Case_list()
   * @model containment="true"
   * @generated
   */
  case_label_list getCase_list();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.case_limb#getCase_list <em>Case list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case list</em>' containment reference.
   * @see #getCase_list()
   * @generated
   */
  void setCase_list(case_label_list value);

  /**
   * Returns the value of the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt</em>' containment reference.
   * @see #setStmt(statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getcase_limb_Stmt()
   * @model containment="true"
   * @generated
   */
  statement getStmt();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.case_limb#getStmt <em>Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt</em>' containment reference.
   * @see #getStmt()
   * @generated
   */
  void setStmt(statement value);

} // case_limb
