/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>case statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getcase_statement()
 * @model
 * @generated
 */
public interface case_statement extends EObject
{
} // case_statement
