/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.expression#getCase_limbs <em>Case limbs</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.expression#getExpressions <em>Expressions</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.expression#getOperators <em>Operators</em>}</li>
 * </ul>
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getexpression()
 * @model
 * @generated
 */
public interface expression extends case_statement
{
  /**
   * Returns the value of the '<em><b>Case limbs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ufcg.compiladores.pascal.case_limb}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case limbs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case limbs</em>' containment reference list.
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getexpression_Case_limbs()
   * @model containment="true"
   * @generated
   */
  EList<case_limb> getCase_limbs();

  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ufcg.compiladores.pascal.simple_expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getexpression_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<simple_expression> getExpressions();

  /**
   * Returns the value of the '<em><b>Operators</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operators</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operators</em>' attribute list.
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getexpression_Operators()
   * @model unique="false"
   * @generated
   */
  EList<String> getOperators();

} // expression
